name: CustomItems
main: fr.mrxtr34m.customitem.Main
version: 1.0.0
author: MrXtr34m

commands:
    customitems:
     usage: /customitem <give|current|list|remove>
     description: Modifying items 
     aliases: [customitems, customitem, ci]